package eu.smartdatalake.simsearch.manager;

import java.util.UUID;

import eu.smartdatalake.simsearch.Constants;

/**
 * Provides identification for the data regarding a specific attribute available from a data source.
 */
public class DatasetIdentifier {

	String hashKey = null;
	private DataSource source;	// Either the directory of the CSV file or a JDBC connection
	private String dataset; 	// The name of the actual dataset, i.e., a CSV file or a database table
	int operation;				// The type of search operation (0: categorical_topk, 1: spatial_knn, 2: numerical_topk) supported by this data source
	String attrValue = null;
	String attrKey = null;
	private boolean queryable = true;   // Unless explicitly specified in the config, a dataset can be involved in similarity search queries 
	private String prefixURL = null;    // URL prefix to be combined with the values in attrKey (assuming this yields resolvable URLs)
	
	// Associate this dataset with its transformed one
	private TransformedDatasetIdentifier transformed = null; // Unless explicitly specified in the config, a dataset is not transformed

	/**
	 * Constructor
	 * @param source  The data source (directory, JDBC connection, or REST API) that provides access to the attribute data.
	 * @param dataset  The name of the dataset (file, table) that contains the attribute data.
	 * @param colValueName  The column name containing the attribute data to be used.
	 * @param nameOperation  The name of the operation supported on this attribute.
	 * @param transformed  Boolean indicating whether this data need be transformed.
	 */
	public DatasetIdentifier(DataSource source, String dataset, String colValueName, String nameOperation, boolean transformed) {
		
		this.source = source;
		this.dataset = dataset;
		this.attrValue = colValueName;
		this.operation = -1;			//Initially, no operation has specified on this attribute
		UUID uuid = generateUUID(nameOperation, transformed);    // Assign a UUID
		this.hashKey = uuid.toString();
	}
	
	/**
	 * Generates a (non-random) Universally Unique Dataset Identifier (UUID).
	 * @param nameOperation  The name of the operation supported on this attribute.
	 * @param transformed  Boolean indicating whether this data need be transformed.
	 * @return  A 128-bit value that represents the UUID.
	 */
	private UUID generateUUID(String nameOperation, boolean transformed) {
		
		UUID uuid = null;
		//UUIDs generated by hashing over the data source, the dataset name, the attribute name, and the operation
		try { 
		    byte[] bytes = (source + dataset + attrValue + nameOperation + (transformed ? "_transformed" : "")).toLowerCase().getBytes("UTF-8"); 
			uuid = UUID.nameUUIDFromBytes(bytes);
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return uuid;
	}
	
	/**
	 * Assign the name of the attribute (column) containing the quaryable values.
	 * @param colName The column name to be assigned.
	 */
	public void setValueAttribute(String colName) {
		
		this.attrValue = colName;   // Applicable only if the input dataset has a header with column names
	}

	/**
	 * Assign the name of the attribute containing the identifiers of the queryable entities.
	 * @param colName The column name to be assigned.
	 */
	public void setKeyAttribute(String colName) {
		
		this.attrKey = colName;   // Applicable only if the input dataset has a header with column names
	}
	
	/**
	 * Assign the type of the search operation to the identifier.
	 * @param operation  An integer representing the type of the search operation (0: CATEGORICAL_TOPK; 1:SPATIAL_KNN ; 2:NUMERICAL_TOPK; 3:PIVOT_BASED).
	 */
	public void setOperation(int operation) {
		this.operation = operation;
	}
	
	/**
	 * Assign a data source to the identifier.
	 * @param source  The data source providing the attribute values, either in-memory (CSV) or in-situ (JDBC).
	 */
	public void setDataSource(DataSource source) {
		this.source = source;
	}
	
	/**
	 * Specify that this attribute data will be involved or not in similarity search requests.
	 * @param queryable Boolean value: True, if this attribute may be specified in similarity search queries; False indicates that this dataset is used solely as a lookup.
	 */
	public void setQueryable(boolean queryable) {
		this.queryable = queryable;
	}

	/**
	 * Prefix to be used in composing URLs and issuing them as entity identifiers in similarity search results.
	 * @param prefixURL  The prefix to be appended to the entity identifiers (coming from values in attrKey).
	 */
	public void setPrefixURL(String prefixURL) {
		this.prefixURL = prefixURL;
	}
	
	// GETTER methods
	
	public String getDatasetName() {
		return this.dataset;
	}
	
	public DataSource getDataSource() {
		return this.source;
	}
	
	public String getHashKey() {
		return this.hashKey;
	}
	
	public String getValueAttribute() {
		return this.attrValue;
	}

	public String getKeyAttribute() {
		return this.attrKey;
	}
	
	public int getOperation() {
		return operation;
	}

	public boolean isQueryable() {
		return queryable;
	}

	public String getPrefixURL() {
		return prefixURL;
	}

	/**
	 * Indicates whether this dataset is only used as a dictionary of names.
	 * @return  True, if the data serves as a dictionary of names; otherwise, False.
	 */
	public boolean isUsedForNames() {
		return (this.operation == Constants.NAME_DICTIONARY);
	}

	/**
	 * Indicates whether this dataset is only used as a dictionary of keywords.
	 * @return  True, if the data serves as a dictionary of sets of keywords; otherwise, False.
	 */
	public boolean isUsedForKeywords() {
		return (this.operation == Constants.KEYWORD_DICTIONARY);
	}

	/**
	 * Indicates whether this dataset is only used as a dictionary of arrays of values (vectors).
	 * @return  True, if the data serves as a dictionary of arrays of values; otherwise, False.
	 */
	public boolean isUsedForVectors() {
		return (this.operation == Constants.VECTOR_DICTIONARY);
	}

	/**
	 * Indicates whether this dataset is a transformed one.
	 * @return  True, if this dataset is not transformed; otherwise, False.
	 */
	public boolean isTransformed() {
		return false;  // Default value;
	}
	
	/**
	 * Indicates whether attribute data (or query) values must be transformed.
	 * @return  True, if attribute data (or query) values must be transformed; otherwise, False.
	 */
	public boolean needsTransform() {
		return false;  // Default value;
	}
	
	/**
	 * Provides the transformed dataset associated with the current dataset.
	 * @return  The associated transformed dataset (e.g., a vector representation of keywords).
	 */
	public TransformedDatasetIdentifier getTransformed() {
		return transformed;
	}

	/**
	 * Associates this dataset with its transformed one based on a vocabulary.
	 * @param transformed  The associated transformed dataset (e.g., a vector representation of keywords).
	 */
	public void setTransformed(TransformedDatasetIdentifier transformed) {
		this.transformed = transformed;
	}

}
